PORTFOLIO/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages_app.urls", namespace="pages")),
    path("users/", include("users_app.urls", namespace="users")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages_app/urls.py
from django.urls import path
from . import views


app_name = "pages"


urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("contact/", views.CreateContactView.as_view(), name="contact"),
    path("review/", views.CreateReviewView.as_view(), name="review"),
]

portfolio_django/PORTFOLIO/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages_app.urls", namespace="pages")),
    path("users/", include("users_app.urls", namespace="users")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio_django/pages_app/urls.py
from django.urls import path
from . import views


app_name = "pages"


urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

portfolio_django/users_app/urls.py
from django.urls import path
from . import views


app_name = "users"


urlpatterns = [

]

users_app/urls.py
from django.urls import path
from . import views


app_name = "users"


urlpatterns = [

]

pages_app/models.py
from django.db import models
from django.db.models.query import Q
from datetime import datetime
from .admin import register_models


class CreatedUpdatedModelNR(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class InfoModel(CreatedUpdatedModelNR):
    image = models.ImageField(upload_to='images/', default="default-entry-image.png")

    started_programming = models.DateField(default=datetime.now)
    instagram_link = models.URLField()
    telegram_link = models.URLField()
    facebook_link = models.URLField()
    github_link = models.URLField()
    contact = models.CharField(max_length=50)

    @property
    def experience(self) -> str:
        return f"{datetime.now().year - self.started_programming.year}+ years"


class SkillCategoryModel(CreatedUpdatedModelNR):
    name = models.CharField(max_length=255)
    icon_class_name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Skill Categories'
        verbose_name = 'Skill Category'


class SkillModel(CreatedUpdatedModelNR):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(SkillCategoryModel, on_delete=models.CASCADE, related_name='skills')

    def __str__(self):
        return f"{self.name} - {self.category}"

    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'


class ReviewModel(CreatedUpdatedModelNR):
    image = models.ImageField(upload_to='images/', default="default-entry-image.png")
    full_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    rating = models.PositiveSmallIntegerField()
    content = models.TextField()

    class Meta:
        verbose_name_plural = "Reviews"
        verbose_name = 'Review'
        constraints = [
            models.CheckConstraint(name="My Rating Check Constraint", check=Q(rating__lte=5, rating__gte=1))
        ]


class ContactModel(CreatedUpdatedModelNR):
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    message = models.TextField()


    def __str__(self):
        return f"{self.name} - {self.email}"

    class Meta:
        verbose_name_plural = 'Contacts'
        verbose_name = 'Contact'


register_models(globals_=globals())

portfolio_django/pages_app/models.py
from django.db import models

# Create your models here.

portfolio_django/users_app/models.py
from django.db import models

# Create your models here.

users_app/models.py
from django.db import models

# Create your models here.

pages_app/forms.py
from django import forms

from .models import ContactModel, ReviewModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = ['name', 'email', 'message']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewModel
        fields = ['image', 'full_name', 'address', 'rating', 'content']

pages_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from . import services
from .forms import ContactForm, ReviewForm
from .models import ContactModel, ReviewModel


class HomePageView(TemplateView):
    template_name = "pages/index.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["info"] = services.get_current_info()
        data["skill_categories"] = services.get_skill_categories()
        data["reviews"] = services.get_reviews()

        return data


class CreateContactView(CreateView):
    form_class = ContactForm
    model = ContactModel
    success_url = reverse_lazy("pages:home")


class CreateReviewView(CreateView):
    form_class = ReviewForm
    model = ReviewModel
    success_url = reverse_lazy("pages:home")

portfolio_django/pages_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/index.html"

portfolio_django/users_app/views.py
from django.shortcuts import render

# Create your views here.

users_app/views.py
from django.shortcuts import render

# Create your views here.

pages_app/templates/pages/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <main id="home-main">

        <section id="home">

            <h1 class="section-title"><a class="a" href="#home">Welcome!</a> Here is a bit about <a class="a" href="#about">Me</a></h1>

            <div class="programmer-image">
                <div class="barrier"></div>
                <img src="{{ info.image.url }}" alt="">
            </div>

            <h2 class="title">Hi!, I'm <a class="a" href="#about">Abdurahimov Fazliddin</a></h2>

            <p>
                I'm a <a class="a" href="#skill">Full Stack</a> developer with more than
                <a class="a" href="#about">{{ info.experience }} years</a> of
                experience. I created many
                <a class="a" href="#skill">Web-Sites</a> and APIs
                for many Web-Sites about many topics e.g. Restaurants,
                Online-Shops and more. And I created
                <a class="a" href="#skill">Telegram Bots</a>
                with great architecture and usable features!
            </p>
            {% include 'layouts/links.html' %}

        </section>

        <section id="about" class="about-section">

            <h1 class="section-title big-title"><b>About Me</b></h1>

            <div class="about-div">

                <h2><a class="a" href="#skill">Full Stack</a> developer with {{ info.experience }} years of experience ...</h2>

                <p>
                    Hello! I'm <a class="a" href="#home">Fazliddin Abdurahimov</a>,
                    a <a href="#skill">Full Stack</a> Web Developer.
                    <br><br>
                    I have been in this field since
                    I was 14. Due to my early interest in
                    programming, I have gained excellent
                    practical experience in building
                    monolithic websites using Python
                    frameworks (<a class="a" href="#skill">Django</a>)
                    and microskill-based backends with Python
                    frameworks (<a class="a" href="#skill">FastAPI</a>).
                    <br><br>
                    I also have significant experience in
                    developing <a class="a" href="#skill">Telegram bots</a> using Python
                    frameworks (<a class="a" href="#skill">Aiogram</a>).
                </p>

            </div>

        </section>

        <section id="skill">

            <h1 class="big-title">A bit about my <a class="a" href="#skill"> Skills</a></h1>

            <div class="skills">
                {% for category in skill_categories %}
                    <div class="{{ category.name }}">
                    <div class="logo">
                        <i class="{{ category.icon_class_name }}"></i>
                    </div>
                    <p class="first-words">
                        {{ category.description }}
                    </p>
                    <ul>
                        {% for skill in category.skills.all %}
                            <li><a href="#">{{ skill.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}
            </div>

        </section>

        <section id="review">
            <h1 class="big-title">Leave Your <a class="a" href="#other-reviews">Reviews</a></h1>

            <form action="{% url 'pages:review' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="review-address">Your full name:</label>
                <input type="text" id="review-address" name="full_name" placeholder="Your Full Name" required>

                <label for="review-address">Your Address:</label>
                <input type="text" id="review-address" name="address" placeholder="Your country and city" required>

                <label for="review-image">Select an Image:</label>
                <input type="file" id="review-image" name="image" accept="image/*" required>

                <label for="review-rate">Rating:</label>
                <select name="rating" id="review-rate" required>
                    <option value="1">⭐☆☆☆☆</option>
                    <option value="2">⭐⭐☆☆☆</option>
                    <option value="3">⭐⭐⭐☆☆</option>
                    <option value="4">⭐⭐⭐⭐☆</option>
                    <option value="5" selected>⭐⭐⭐⭐⭐</option>
                </select>

                <label for="text-area">Your Review:</label>
                <textarea name="content" id="text-area" cols="30" rows="5" placeholder="Write some cool review here :)" required></textarea>

                <button type="submit">Post</button>
            </form>

            
        </section>

        <section id="other-reviews">
            <h1 class="big-title">Other People's <a class="a" href="#review">Review</a>s</h1>
            {% for review in reviews %}
                <div class="review-cart">

                <div class="review-header">

                    <div class="img">
                        <img class="review-img" src="{{ review.image.url }}" alt="">
                    </div>

                    <div class="right-header-part">
                        <h3>{{ review.full_name }}</h3>
                        <small>{{ review.address }}</small>
                    </div>

                </div>

                {% if review.rating == 5 %}
                    <p class="ratings">⭐⭐⭐⭐⭐</p>

                {% elif review.rating == 4 %}
                    <p class="ratings">⭐⭐⭐⭐☆</p>

                {% elif review.rating == 3 %}
                    <p class="ratings">⭐⭐⭐☆☆</p>

                {% elif review.rating == 2 %}
                    <p class="ratings">⭐⭐☆☆☆</p>

                {% elif review.rating == 1 %}
                    <p class="ratings">⭐☆☆☆☆</p>

                {% endif %}

                <p class="review-content">
                    {{ review.content }}
                </p>

                <small>{{ review.updated_at|timesince }}</small>

            </div>
            {% endfor %}
        </section>

        <section id="contact">

            <h1 class="big-title">Contact with <a class="a" href="#home">Me</a></h1>

            <form id="contact-form" action="{% url 'pages:contact' %}" method="post">
                {% csrf_token %}
                <input name="name" type="text" placeholder="Your Full name" required>
                <input name="email" type="email" placeholder="Your Email address" required>
                <textarea name="message" id="" cols="" rows="" placeholder="The Message" required></textarea>
                <button type="submit">Send Message</button>
            </form>

            {% include 'layouts/links.html' %}

        </section>

    </main>

{% endblock %}

portfolio_django/pages_app/templates/pages/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <main id="home-main">

        <section id="home">

            <h1 class="section-title"><a class="a" href="#home">Welcome!</a> Here is a bit about <a class="a" href="#about">Me</a></h1>

            <div class="programmer-image">
                <div class="barrier"></div>
                <img src="{% static 'images/programmer.png' %}" alt="">
            </div>

            <h2>Hi!, I'm <a class="a" href="#about">Abdurahimov Fazliddin</a></h2>

            <p>
                I'm a <a class="a" href="#skills">Full Stack</a> developer with more than
                <a class="a" href="#about">2 years</a> of
                experience. I created many
                <a class="a" href="#services">Web-Sites</a> and APIs
                for many Web-Sites about many topics e.g. Restaurants,
                Online-Shops and more. And I created
                <a class="a" href="#services">Telegram Bots</a>
                with great architecture and usable features!
            </p>
        </section>

        <section id="about" class="about-section">

            <h1 class="section-title big-title"><b>About Me</b></h1>

            <div class="about-div">

                <h2><a class="a" href="#skills">Full Stack</a> developer with 2+ years of experience ...</h2>

                <p>
                    Hello! I'm <a class="a" href="#home">Fazliddin Abdurahimov</a>,
                    a <a href="#skills">Full Stack</a> Web Developer.
                    <br><br>
                    I have been in this field since
                    I was 14. Due to my early interest in
                    programming, I have gained excellent
                    practical experience in building
                    monolithic websites using Python
                    frameworks (<a class="a" href="#skills">Django</a>)
                    and microservice-based backends with Python
                    frameworks (<a class="a" href="#skills">FastAPI</a>).
                    <br><br>
                    I also have significant experience in
                    developing <a class="a" href="#services">Telegram bots</a> using Python
                    frameworks (<a class="a" href="#skills">Aiogram</a>).
                </p>

            </div>

        </section>
    
        <section id="review">
            <h1 class="big-title">Leave your review</h1>

            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <label for="review-address">Your Address:</label>
                <input type="text" id="review-address" name="address" placeholder="Your country and city" required>

                <label for="review-image">Select an Image:</label>
                <input type="file" id="review-image" name="image" accept="image/*" required>

                <label for="review-rate">Rating:</label>
                <select name="rating" id="review-rate" required>
                    <option value="1">⭐☆☆☆☆</option>
                    <option value="2">⭐⭐☆☆☆</option>
                    <option value="3">⭐⭐⭐☆☆</option>
                    <option value="4">⭐⭐⭐⭐☆</option>
                    <option value="5" selected>⭐⭐⭐⭐⭐</option>
                </select>

                <label for="text-area">Your Review:</label>
                <textarea name="review" id="text-area" cols="30" rows="5" placeholder="Write some cool review here :)" required></textarea>

                <button type="submit">Post</button>
            </form>

            
        </section>

        <section id="other-reviews">
            <div class="review-cart">

                <div class="review-header">

                    <div class="img">
                        <img class="review-img" src="" alt="">
                    </div>

                    <div class="right-header-part">
                        <h3>Name</h3>
                        <p>address</p>
                    </div>

                </div>

                <p class="ratings">⭐⭐⭐⭐⭐</p>

                <p class="review-content">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem illum in nam
                    non provident quo rerum sint soluta. Dolor eius
                    error facere fugiat maxime nesciunt, odit placeat
                    quis suscipit vero!
                </p>

                <p>2024.05.27 (4 months ago)</p>

            </div>
            <div class="review-cart">

                <div class="review-header">

                    <div class="img">
                        <img class="review-img" src="" alt="">
                    </div>

                    <div class="right-header-part">
                        <h3>Name</h3>
                        <p>address</p>
                    </div>

                </div>

                <p class="ratings">⭐⭐⭐⭐⭐</p>

                <p class="review-content">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem illum in nam
                    non provident quo rerum sint soluta. Dolor eius
                    error facere fugiat maxime nesciunt, odit placeat
                    quis suscipit vero!
                </p>

                <p>2024.05.27 (4 months ago)</p>

            </div>
            <div class="review-cart">

                <div class="review-header">

                    <div class="img">
                        <img class="review-img" src="" alt="">
                    </div>

                    <div class="right-header-part">
                        <h3>Name</h3>
                        <p>address</p>
                    </div>

                </div>

                <p class="ratings">⭐⭐⭐⭐⭐</p>

                <p class="review-content">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem illum in nam
                    non provident quo rerum sint soluta. Dolor eius
                    error facere fugiat maxime nesciunt, odit placeat
                    quis suscipit vero!
                </p>

                <p>2024.05.27 (4 months ago)</p>

            </div>
            <div class="review-cart">

                <div class="review-header">

                    <div class="img">
                        <img class="review-img" src="" alt="">
                    </div>

                    <div class="right-header-part">
                        <h3>Name</h3>
                        <p>address</p>
                    </div>

                </div>

                <p class="ratings">⭐⭐⭐⭐⭐</p>

                <p class="review-content">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem illum in nam
                    non provident quo rerum sint soluta. Dolor eius
                    error facere fugiat maxime nesciunt, odit placeat
                    quis suscipit vero!
                </p>

                <p>2024.05.27 (4 months ago)</p>

            </div>
        </section>

    </main>

{% endblock %}

portfolio_django/templates/layouts/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'css/layouts/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/layouts/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/layouts/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/pages/index.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
</head>
<body>
    
    {% include 'layouts/header.html' %}
    
    {% block content %}{% endblock %}

    {% include 'layouts/footer.html' %}

</body>
</html>

portfolio_django/templates/layouts/footer.html
<footer>
    
</footer>

portfolio_django/templates/layouts/header.html
<header>
    <nav>

        <div class="logo">
            <a href="{% url 'pages:home' %}"><i class="fa-solid fa-address-card"></i></a>
        </div>
        
        <div class="urls">
            <ul class="header-links">
                <li><a href="{% url 'pages:home' %}"><i class="fa-solid fa-house"></i> Home</a></li>
                <li><a href="#"><i class="fa-solid fa-question"></i> About</a></li>
                <li><a href="#"><i class="fa-solid fa-bolt-lightning"></i> Skills</a></li>
                <li><a href="#"><i class="fa-solid fa-briefcase"></i> Services</a></li>
                <li><a href="#"><i class="fa-solid fa-user"></i> Portfolio</a></li>
                <li><a href="#"><i class="fa-solid fa-comment"></i> Reviews</a></li>
            </ul>
    
            <a class="login-btn" href="#">Login</a>
        </div>
        
    </nav>
</header>

templates/layouts/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'css/layouts/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/layouts/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/layouts/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/pages/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/layouts/links.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="icon" href="{% static 'images/website-logo.png' %}" type="image/png">
</head>
<body>
    
    {% include 'layouts/header.html' %}
    
    {% block content %}{% endblock %}

    {% include 'layouts/footer.html' %}

</body>
</html>

templates/layouts/footer.html
<footer>
    
</footer>

templates/layouts/header.html
<header>
    <nav>

        <div class="logo">
            <a href="{% url 'pages:home' %}"><i class="fa-solid fa-address-card"></i></a>
        </div>
        
        <div class="urls">
            <ul class="header-links">
                <li><a href="{% url 'pages:home' %}#home"><i class="fa-solid fa-house"></i> Home</a></li>
                <li><a href="{% url 'pages:home' %}#about"><i class="fa-solid fa-question"></i> About</a></li>
                <li><a href="{% url 'pages:home' %}#skill"><i class="fa-solid fa-bolt-lightning"></i> Skills</a></li>
                <li><a title="Open a github.com" href="{{ info.github_link }}"><i class="fa-solid fa-user"></i> Portfolio</a></li>
                <li><a href="{% url 'pages:home' %}#review"><i class="fa-solid fa-comment"></i> Reviews</a></li>
            </ul>
    
            <a class="contact-btn" href="#contact">Contact</a>
        </div>
        
    </nav>
</header>

templates/layouts/links.html
<div class="links">

    <a href="{{ info.instagram_link }}" title="Instagram"><i class="fa-brands fa-instagram"></i></a>
    <a href="{{ info.facebook_link }}" title="FaceBook"><i class="fa-brands fa-facebook-f"></i></a>
    <a href="{{ info.telegram_link }}" title="Telegram"><i class="fa-brands fa-telegram"></i></a>
    <a href="{{ info.github_link }}" title="GitHub"><i class="fa-brands fa-github"></i></a>
    <a href="tel:{{ info.contact }}" title="Call Me" aria-label="Call Me">
        <i class="fa-solid fa-phone"></i>
    </a>

</div>